Drive Live For Speed Server: Drive_LFSS.Socket_.InSim Class Reference
Drive_LFSS.Socket_.InSim Class Reference
Public Member Functions
InSim (InSimSetting _inSimSetting)
InSim ()
void exit ()
void connect ()
Protected Attributes
Store packetStore
Properties
InSim_Socket_State socketFlag [get]
Private Member Functions
void SocketReceive ()
void TcpSend ()
void UdpSend ()
void TcpReceive ()
void UdpReceive ()
Private Attributes
InSim_Socket_State socketStatus = InSim_Socket_State.INSIM_DISCONNECTED
InSimSetting inSimSetting
bool runThreadSocketReceive = false
Thread threadSocketReceive
TcpClient tcpClient
NetworkStream tcpSocket
UdpClient udpClient
Network udpSocket
IPEndPoint udpIpEndPoint
Detailed Description
Definition at line 14 of file insim.cs.
Constructor & Destructor Documentation
Drive_LFSS.Socket_.InSim.InSim (InSimSetting _inSimSetting)
Definition at line 16 of file insim.cs.
References Drive_LFSS.Socket_.InSimSetting.adminPassword, Drive_LFSS.Socket_.InSimSetting.connectionName, Drive_LFSS.Socket_.InSim.inSimSetting, Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Socket_.InSim.SocketReceive(), Drive_LFSS.Socket_.InSimSetting.tcpPort, Drive_LFSS.Socket_.InSim.threadSocketReceive, and Drive_LFSS.Socket_.InSimSetting.udpPort.
Drive_LFSS.Socket_.InSim.InSim ()
Definition at line 43 of file insim.cs.
Member Function Documentation
void Drive_LFSS.Socket_.InSim.exit ()
Definition at line 57 of file insim.cs.
References Drive_LFSS.Socket_.Store.AddToTcpSendingQueud(), Drive_LFSS.Socket_.InSim.inSimSetting, Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Socket_.InSim.runThreadSocketReceive, Drive_LFSS.Socket_.InSim.socketStatus, Drive_LFSS.Socket_.InSim.tcpClient, Drive_LFSS.Socket_.InSim.threadSocketReceive, Drive_LFSS.Socket_.InSim.udpClient, and Drive_LFSS.Socket_.InSimSetting.udpPort.
void Drive_LFSS.Socket_.InSim.connect ()
Definition at line 77 of file insim.cs.
References Drive_LFSS.Socket_.Store.AddToTcpSendingQueud(), Drive_LFSS.Socket_.InSimSetting.adminPassword, Drive_LFSS.Socket_.InSimSetting.CommandPrefix, Drive_LFSS.Socket_.InSimSetting.connectionName, Drive_LFSS.Socket_.InSimSetting.Flags, Drive_LFSS.Socket_.InSim.inSimSetting, Drive_LFSS.Socket_.InSimSetting.MCI_NLP_Interval, Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Socket_.InSim.runThreadSocketReceive, Drive_LFSS.Socket_.InSimSetting.serverIp, Drive_LFSS.Socket_.InSim.SocketReceive(), Drive_LFSS.Socket_.InSim.socketStatus, Drive_LFSS.Socket_.InSim.tcpClient, Drive_LFSS.Socket_.InSimSetting.tcpPort, Drive_LFSS.Socket_.InSim.tcpSocket, Drive_LFSS.Socket_.InSim.threadSocketReceive, Drive_LFSS.Socket_.InSim.udpClient, Drive_LFSS.Socket_.InSim.udpIpEndPoint, and Drive_LFSS.Socket_.InSimSetting.udpPort.
void Drive_LFSS.Socket_.InSim.SocketReceive () [private]
Definition at line 112 of file insim.cs.
References Drive_LFSS.Socket_.InSim.runThreadSocketReceive, Drive_LFSS.Socket_.InSim.TcpReceive(), Drive_LFSS.Socket_.InSim.TcpSend(), Drive_LFSS.Socket_.InSim.UdpReceive(), and Drive_LFSS.Socket_.InSim.UdpSend().
Referenced by Drive_LFSS.Socket_.InSim.connect(), and Drive_LFSS.Socket_.InSim.InSim().
void Drive_LFSS.Socket_.InSim.TcpSend () [private]
Definition at line 123 of file insim.cs.
References Drive_LFSS.Socket_.Store.NextTcpSendQueud(), Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Socket_.InSim.tcpClient, and Drive_LFSS.Socket_.InSim.tcpSocket.
Referenced by Drive_LFSS.Socket_.InSim.SocketReceive().
void Drive_LFSS.Socket_.InSim.UdpSend () [private]
Definition at line 138 of file insim.cs.
References Drive_LFSS.Socket_.Store.NextUdpSendQueud(), Drive_LFSS.Socket_.InSim.packetStore, and Drive_LFSS.Socket_.InSim.udpClient.
Referenced by Drive_LFSS.Socket_.InSim.SocketReceive().
void Drive_LFSS.Socket_.InSim.TcpReceive () [private]
Definition at line 147 of file insim.cs.
References Drive_LFSS.Socket_.Store.AddToTcpReceiveQueud(), Drive_LFSS.Socket_.InSim.packetStore, and Drive_LFSS.Socket_.InSim.tcpSocket.
Referenced by Drive_LFSS.Socket_.InSim.SocketReceive().
void Drive_LFSS.Socket_.InSim.UdpReceive () [private]
Definition at line 167 of file insim.cs.
References Drive_LFSS.Socket_.Store.AddToUdpReceiveQueud(), Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Socket_.InSim.udpClient, and Drive_LFSS.Socket_.InSim.udpIpEndPoint.
Referenced by Drive_LFSS.Socket_.InSim.SocketReceive().
Member Data Documentation
Store Drive_LFSS.Socket_.InSim.packetStore [protected]
Definition at line 44 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), Drive_LFSS.Socket_.InSim.InSim(), Drive_LFSS.Socket_.InSim.TcpReceive(), Drive_LFSS.Socket_.InSim.TcpSend(), Drive_LFSS.Socket_.InSim.UdpReceive(), Drive_LFSS.Socket_.InSim.UdpSend(), and Drive_LFSS.Server_.Server.update().
InSim_Socket_State Drive_LFSS.Socket_.InSim.socketStatus = InSim_Socket_State.INSIM_DISCONNECTED [private]
Definition at line 45 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), and Drive_LFSS.Socket_.InSim.exit().
InSimSetting Drive_LFSS.Socket_.InSim.inSimSetting [private]
Definition at line 47 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), and Drive_LFSS.Socket_.InSim.InSim().
bool Drive_LFSS.Socket_.InSim.runThreadSocketReceive = false [private]
Definition at line 49 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), and Drive_LFSS.Socket_.InSim.SocketReceive().
Thread Drive_LFSS.Socket_.InSim.threadSocketReceive [private]
Definition at line 50 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), and Drive_LFSS.Socket_.InSim.InSim().
TcpClient Drive_LFSS.Socket_.InSim.tcpClient [private]
Definition at line 51 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), and Drive_LFSS.Socket_.InSim.TcpSend().
NetworkStream Drive_LFSS.Socket_.InSim.tcpSocket [private]
Definition at line 52 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.TcpReceive(), and Drive_LFSS.Socket_.InSim.TcpSend().
UdpClient Drive_LFSS.Socket_.InSim.udpClient [private]
Definition at line 53 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), Drive_LFSS.Socket_.InSim.UdpReceive(), and Drive_LFSS.Socket_.InSim.UdpSend().
Network Drive_LFSS.Socket_.InSim.udpSocket [private]
Definition at line 54 of file insim.cs.
IPEndPoint Drive_LFSS.Socket_.InSim.udpIpEndPoint [private]
Definition at line 55 of file insim.cs.
Referenced by Drive_LFSS.Socket_.InSim.connect(), and Drive_LFSS.Socket_.InSim.UdpReceive().
Property Documentation
InSim_Socket_State Drive_LFSS.Socket_.InSim.socketFlag [get]
Definition at line 186 of file insim.cs.
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/network/insim.cs