Drive Live For Speed Server: Drive_LFSS.Server_.CommandServer Class Reference
Drive_LFSS.Server_.CommandServer Class Reference
Public Member Functions
CommandServer (ushort _serverId)
ushort GetServerId ()
void Exec (Licence licence, string commandText)
Private Member Functions
delegate void CommandDelegate (Licence licence, string commandText)
void Exit (Licence licence, string commandText)
void Kick (Licence licence, string commandText)
Private Attributes
ushort serverId
Dictionary< string, CommandName > command = new Dictionary<string,CommandName> ()
Classes
struct CommandName
Detailed Description
Definition at line 10 of file command.cs.
Constructor & Destructor Documentation
Drive_LFSS.Server_.CommandServer.CommandServer (ushort _serverId)
Definition at line 12 of file command.cs.
References Drive_LFSS.Server_.CommandServer.command, Drive_LFSS.Server_.CommandServer.CommandDelegate(), Drive_LFSS.Server_.CommandServer.Exit(), Drive_LFSS.Server_.CommandServer.Kick(), and Drive_LFSS.Server_.CommandServer.serverId.
Member Function Documentation
delegate void Drive_LFSS.Server_.CommandServer.CommandDelegate (Licence licence, string commandText) [private]
Referenced by Drive_LFSS.Server_.CommandServer.CommandServer().
ushort Drive_LFSS.Server_.CommandServer.GetServerId ()
Definition at line 37 of file command.cs.
References Drive_LFSS.Server_.CommandServer.serverId.
void Drive_LFSS.Server_.CommandServer.Exec (Licence licence, string commandText)
Definition at line 41 of file command.cs.
References Drive_LFSS.Server_.CommandServer.command, Drive_LFSS.Game_.Licence.GetConnectionPlayerName(), Drive_LFSS.Game_.Licence.IsAdmin(), and Drive_LFSS.Server_.CommandServer.serverId.
Referenced by Drive_LFSS.Server_.Server.MSO_MessageOut().
void Drive_LFSS.Server_.CommandServer.Exit (Licence licence, string commandText) [private]
Definition at line 54 of file command.cs.
Referenced by Drive_LFSS.Server_.CommandServer.CommandServer().
void Drive_LFSS.Server_.CommandServer.Kick (Licence licence, string commandText) [private]
Definition at line 59 of file command.cs.
Referenced by Drive_LFSS.Server_.CommandServer.CommandServer().
Member Data Documentation
ushort Drive_LFSS.Server_.CommandServer.serverId [private]
Definition at line 21 of file command.cs.
Referenced by Drive_LFSS.Server_.CommandServer.CommandServer(), Drive_LFSS.Server_.CommandServer.Exec(), and Drive_LFSS.Server_.CommandServer.GetServerId().
Dictionary<string,CommandName> Drive_LFSS.Server_.CommandServer.command = new Dictionary<string,CommandName> () [private]
Definition at line 35 of file command.cs.
Referenced by Drive_LFSS.Server_.CommandServer.CommandServer(), and Drive_LFSS.Server_.CommandServer.Exec().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/server/command.cs