Drive Live For Speed Server: Drive_LFSS.Log_.sLog Class Reference
Drive_LFSS.Log_.sLog Class Reference
Public Member Functions
sLog (ushort _serverId)
sLog ()
void error (string msg)
void normal (string msg)
void chat (string msg)
void command (string msg)
void debug (string msg)
void network (string msg)
void ping (string msg)
Static Public Member Functions
static bool Init ()
static void flush ()
Public Attributes
LogType logDisable = LogType.LOG_FULL
ushort serverId = 0
Private Member Functions
string GetServerName ()
Private Attributes
const string LOG_FILE_PATH = @".\drive_lfss.log"
Static Private Attributes
static System.IO.StreamWriter streamWriter
static bool isInitialized = false
Detailed Description
Definition at line 19 of file log.cs.
Constructor & Destructor Documentation
Drive_LFSS.Log_.sLog.sLog (ushort _serverId)
Definition at line 21 of file log.cs.
References Drive_LFSS.Log_.sLog.isInitialized, and Drive_LFSS.Log_.sLog.serverId.
Drive_LFSS.Log_.sLog.sLog ()
Definition at line 29 of file log.cs.
References Drive_LFSS.Log_.sLog.isInitialized, and Drive_LFSS.Log_.sLog.serverId.
Member Function Documentation
static bool Drive_LFSS.Log_.sLog.Init () [static]
Definition at line 44 of file log.cs.
References Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Log_.sLog.isInitialized, Drive_LFSS.Log_.sLog.LOG_FILE_PATH, and Drive_LFSS.Log_.sLog.streamWriter.
static void Drive_LFSS.Log_.sLog.flush () [static]
Definition at line 59 of file log.cs.
References Drive_LFSS.Log_.sLog.streamWriter.
void Drive_LFSS.Log_.sLog.error (string msg)
Definition at line 63 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
Referenced by Drive_LFSS.Program.CaptureConsoleCommand(), Drive_LFSS.Program.ConsoleExitTimer(), Drive_LFSS.Program.DisgraceExit(), Drive_LFSS.Log_.sLog.Init(), Drive_LFSS.Server_.Server.LicenceJoinHost(), Drive_LFSS.Server_.Server.Server(), and Drive_LFSS.Program.UnHandleException().
void Drive_LFSS.Log_.sLog.normal (string msg)
Definition at line 76 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
Referenced by Drive_LFSS.Program.Main(), Drive_LFSS.Server_.Server.VER_InSimVersionInformation(), and Drive_LFSS.Program.WriteBanner().
void Drive_LFSS.Log_.sLog.chat (string msg)
Definition at line 89 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
Referenced by Drive_LFSS.Server_.Server.MSO_MessageOut().
void Drive_LFSS.Log_.sLog.command (string msg)
Definition at line 102 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
void Drive_LFSS.Log_.sLog.debug (string msg)
Definition at line 115 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
Referenced by Drive_LFSS.Server_.Server.AXC_AutocrossCleared(), Drive_LFSS.Server_.Server.AXI_AutocrossLayoutInformation(), Drive_LFSS.Server_.Server.AXO_PlayerHitsAutocrossObject(), Drive_LFSS.Server_.Server.BFN_PlayerRequestsButtons(), Drive_LFSS.Server_.Server.BTC_ButtonClicked(), Drive_LFSS.Server_.Server.BTT_TextBoxOkClicked(), Drive_LFSS.Server_.Server.CCH_CameraChanged(), Drive_LFSS.Server_.Server.CLR_RaceCleared(), Drive_LFSS.Server_.Server.CPP_CameraPosition(), Drive_LFSS.Server_.Server.CPR_ClientRenames(), Drive_LFSS.Server_.Server.CRS_PlayerResetsCar(), Drive_LFSS.Server_.Server.FIN_PlayerFinishedRaces(), Drive_LFSS.Server_.Server.FLG_FlagChanged(), Drive_LFSS.Server_.Server.III_InSimInfo(), Drive_LFSS.Server_.Server.ISM_MultiplayerInformation(), Drive_LFSS.Server_.Server.LAP_PlayerCompletesLap(), Drive_LFSS.Server_.Server.LicenceJoinHost(), Drive_LFSS.Server_.Server.LicenceLeaveHost(), Drive_LFSS.Server_.Server.MCI_CarInformation(), Drive_LFSS.Server_.Server.MPE_MultiplayerEnd(), Drive_LFSS.Server_.Server.MSO_MessageOut(), Drive_LFSS.Server_.Server.NLP_LapNode(), Drive_LFSS.Server_.Server.NPL_PlayerJoinsRace(), Drive_LFSS.Server_.Server.PEN_PenaltyChanged(), Drive_LFSS.Server_.Server.PFL_PlayerFlagsChanged(), Drive_LFSS.Server_.Server.PIT_PlayerStopsAtPit(), Drive_LFSS.Server_.Server.PLA_PitLaneChanged(), Drive_LFSS.Server_.Server.PLL_PlayerLeavesRace(), Drive_LFSS.Server_.Server.PLP_PlayerGoesToGarage(), Drive_LFSS.Server_.Server.PSF_PitStopFinished(), Drive_LFSS.Server_.Server.REN_RaceEnds(), Drive_LFSS.Server_.Server.REO_RaceStartOrder(), Drive_LFSS.Server_.Server.RES_RaceOrQualifyingResult(), Drive_LFSS.Server_.Server.RST_RaceStart(), Drive_LFSS.Server_.Server.RTP_RaceTime(), Drive_LFSS.Server_.Server.SPX_SplitTime(), Drive_LFSS.Server_.Server.STA_StateChanged(), Drive_LFSS.Server_.Server.TOC_PlayerCarTakeOver(), Drive_LFSS.Server_.Server.update(), Drive_LFSS.Server_.Server.VER_InSimVersionInformation(), Drive_LFSS.Server_.Server.VTA_VoteAction(), Drive_LFSS.Server_.Server.VTC_VoteCanceled(), and Drive_LFSS.Server_.Server.VTN_VoteNotify().
void Drive_LFSS.Log_.sLog.network (string msg)
Definition at line 128 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
void Drive_LFSS.Log_.sLog.ping (string msg)
Definition at line 141 of file log.cs.
References Drive_LFSS.Log_.sLog.GetServerName(), Drive_LFSS.Log_.sLog.logDisable, and Drive_LFSS.Log_.sLog.streamWriter.
Referenced by Drive_LFSS.Server_.Server.REPLY_PingReplay().
string Drive_LFSS.Log_.sLog.GetServerName () [private]
Definition at line 155 of file log.cs.
References Drive_LFSS.Log_.sLog.serverId.
Referenced by Drive_LFSS.Log_.sLog.chat(), Drive_LFSS.Log_.sLog.command(), Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Log_.sLog.network(), Drive_LFSS.Log_.sLog.normal(), and Drive_LFSS.Log_.sLog.ping().
Member Data Documentation
LogType Drive_LFSS.Log_.sLog.logDisable = LogType.LOG_FULL
Definition at line 37 of file log.cs.
Referenced by Drive_LFSS.Log_.sLog.chat(), Drive_LFSS.Log_.sLog.command(), Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Log_.sLog.network(), Drive_LFSS.Log_.sLog.normal(), and Drive_LFSS.Log_.sLog.ping().
ushort Drive_LFSS.Log_.sLog.serverId = 0
Definition at line 38 of file log.cs.
Referenced by Drive_LFSS.Log_.sLog.GetServerName(), and Drive_LFSS.Log_.sLog.sLog().
const string Drive_LFSS.Log_.sLog.LOG_FILE_PATH = @".\drive_lfss.log" [private]
Definition at line 40 of file log.cs.
Referenced by Drive_LFSS.Log_.sLog.Init().
System.IO.StreamWriter Drive_LFSS.Log_.sLog.streamWriter [static, private]
Definition at line 41 of file log.cs.
Referenced by Drive_LFSS.Log_.sLog.chat(), Drive_LFSS.Log_.sLog.command(), Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Log_.sLog.flush(), Drive_LFSS.Log_.sLog.Init(), Drive_LFSS.Log_.sLog.network(), Drive_LFSS.Log_.sLog.normal(), and Drive_LFSS.Log_.sLog.ping().
bool Drive_LFSS.Log_.sLog.isInitialized = false [static, private]
Definition at line 42 of file log.cs.
Referenced by Drive_LFSS.Log_.sLog.Init(), and Drive_LFSS.Log_.sLog.sLog().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/log/log.cs