Drive Live For Speed Server: Drive_LFSS.Socket_.Store Class Reference
Drive_LFSS.Socket_.Store Class Reference
Public Member Functions
Store ()
void AddToUdpReceiveQueud (Packet _serverPacket)
void AddToUdpSendingQueud (Packet _serverPacket)
void AddToTcpReceiveQueud (Packet _serverPacket)
void AddToTcpSendingQueud (Packet _serverPacket)
object NextUdpSendQueud (bool _returnStruct)
byte[] NextUdpSendQueud ()
object NextTcpSendQueud (bool _returnStruct)
byte[] NextTcpSendQueud ()
object NextUdpReceiveQueud (bool _returnStruct)
byte[] NextUdpReceiveQueud ()
object NextTcpReceiveQueud (bool _returnStruct)
byte[] NextTcpReceiveQueud ()
Public Attributes
List< Packet > udpReceivedQueud
List< Packet > udpSendingQueud
List< Packet > tcpReceivedQueud
List< Packet > tcpSendingQueud
Private Member Functions
object toStruct (Packet_Type _packetType, byte[] _data)
Private Attributes
PacketStructureList struturedPacket
Detailed Description
Definition at line 9 of file store.cs.
Constructor & Destructor Documentation
Drive_LFSS.Socket_.Store.Store ()
Definition at line 11 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, Drive_LFSS.Socket_.Store.tcpReceivedQueud, Drive_LFSS.Socket_.Store.tcpSendingQueud, Drive_LFSS.Socket_.Store.udpReceivedQueud, and Drive_LFSS.Socket_.Store.udpSendingQueud.
Member Function Documentation
void Drive_LFSS.Socket_.Store.AddToUdpReceiveQueud (Packet _serverPacket)
Definition at line 26 of file store.cs.
References Drive_LFSS.Socket_.Store.udpReceivedQueud.
Referenced by Drive_LFSS.Socket_.InSim.UdpReceive().
void Drive_LFSS.Socket_.Store.AddToUdpSendingQueud (Packet _serverPacket)
Definition at line 33 of file store.cs.
References Drive_LFSS.Socket_.Store.udpSendingQueud.
void Drive_LFSS.Socket_.Store.AddToTcpReceiveQueud (Packet _serverPacket)
Definition at line 41 of file store.cs.
References Drive_LFSS.Socket_.Store.tcpReceivedQueud.
Referenced by Drive_LFSS.Socket_.InSim.TcpReceive().
void Drive_LFSS.Socket_.Store.AddToTcpSendingQueud (Packet _serverPacket)
Definition at line 48 of file store.cs.
References Drive_LFSS.Socket_.Store.tcpSendingQueud.
Referenced by Drive_LFSS.Socket_.InSim.connect(), Drive_LFSS.Socket_.InSim.exit(), and Drive_LFSS.Server_.Server.update().
object Drive_LFSS.Socket_.Store.NextUdpSendQueud (bool _returnStruct)
Definition at line 56 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, Drive_LFSS.Socket_.Store.toStruct(), Drive_LFSS.Socket_.Store.udpReceivedQueud, and Drive_LFSS.Socket_.Store.udpSendingQueud.
Referenced by Drive_LFSS.Socket_.InSim.UdpSend().
byte [] Drive_LFSS.Socket_.Store.NextUdpSendQueud ()
Definition at line 71 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, and Drive_LFSS.Socket_.Store.udpSendingQueud.
object Drive_LFSS.Socket_.Store.NextTcpSendQueud (bool _returnStruct)
Definition at line 89 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, Drive_LFSS.Socket_.Store.tcpSendingQueud, and Drive_LFSS.Socket_.Store.toStruct().
Referenced by Drive_LFSS.Socket_.InSim.TcpSend().
byte [] Drive_LFSS.Socket_.Store.NextTcpSendQueud ()
Definition at line 104 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, and Drive_LFSS.Socket_.Store.tcpSendingQueud.
object Drive_LFSS.Socket_.Store.NextUdpReceiveQueud (bool _returnStruct)
Definition at line 123 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, Drive_LFSS.Socket_.Store.toStruct(), and Drive_LFSS.Socket_.Store.udpReceivedQueud.
byte [] Drive_LFSS.Socket_.Store.NextUdpReceiveQueud ()
Definition at line 138 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, and Drive_LFSS.Socket_.Store.udpReceivedQueud.
object Drive_LFSS.Socket_.Store.NextTcpReceiveQueud (bool _returnStruct)
Definition at line 156 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, Drive_LFSS.Socket_.Store.toStruct(), and Drive_LFSS.Socket_.Store.udpReceivedQueud.
byte [] Drive_LFSS.Socket_.Store.NextTcpReceiveQueud ()
Definition at line 171 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket, and Drive_LFSS.Socket_.Store.tcpReceivedQueud.
object Drive_LFSS.Socket_.Store.toStruct (Packet_Type _packetType, byte[] _data) [private]
Definition at line 190 of file store.cs.
References Drive_LFSS.Socket_.Store.struturedPacket.
Referenced by Drive_LFSS.Socket_.Store.NextTcpReceiveQueud(), Drive_LFSS.Socket_.Store.NextTcpSendQueud(), Drive_LFSS.Socket_.Store.NextUdpReceiveQueud(), and Drive_LFSS.Socket_.Store.NextUdpSendQueud().
Member Data Documentation
PacketStructureList Drive_LFSS.Socket_.Store.struturedPacket [private]
Definition at line 20 of file store.cs.
Referenced by Drive_LFSS.Socket_.Store.NextTcpReceiveQueud(), Drive_LFSS.Socket_.Store.NextTcpSendQueud(), Drive_LFSS.Socket_.Store.NextUdpReceiveQueud(), Drive_LFSS.Socket_.Store.NextUdpSendQueud(), Drive_LFSS.Socket_.Store.Store(), and Drive_LFSS.Socket_.Store.toStruct().
List<Packet> Drive_LFSS.Socket_.Store.udpReceivedQueud
Definition at line 21 of file store.cs.
Referenced by Drive_LFSS.Socket_.Store.AddToUdpReceiveQueud(), Drive_LFSS.Socket_.Store.NextTcpReceiveQueud(), Drive_LFSS.Socket_.Store.NextUdpReceiveQueud(), Drive_LFSS.Socket_.Store.NextUdpSendQueud(), and Drive_LFSS.Socket_.Store.Store().
List<Packet> Drive_LFSS.Socket_.Store.udpSendingQueud
Definition at line 22 of file store.cs.
Referenced by Drive_LFSS.Socket_.Store.AddToUdpSendingQueud(), Drive_LFSS.Socket_.Store.NextUdpSendQueud(), and Drive_LFSS.Socket_.Store.Store().
List<Packet> Drive_LFSS.Socket_.Store.tcpReceivedQueud
Definition at line 23 of file store.cs.
Referenced by Drive_LFSS.Socket_.Store.AddToTcpReceiveQueud(), Drive_LFSS.Socket_.Store.NextTcpReceiveQueud(), and Drive_LFSS.Socket_.Store.Store().
List<Packet> Drive_LFSS.Socket_.Store.tcpSendingQueud
Definition at line 24 of file store.cs.
Referenced by Drive_LFSS.Socket_.Store.AddToTcpSendingQueud(), Drive_LFSS.Socket_.Store.NextTcpSendQueud(), and Drive_LFSS.Socket_.Store.Store().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/network/store.cs