Drive Live For Speed Server: Drive_LFSS.Server_.Session Class Reference
Drive_LFSS.Server_.Session Class Reference
Static Public Member Functions
static void LoadServerConfig ()
static void update (uint diff)
static void ConnectToServerId (ushort serverId)
static void exit ()
Static Public Attributes
static Dictionary< ushort,
ServerStruct > serverList = new Dictionary<ushort, ServerStruct>()
Classes
struct ServerStruct
Detailed Description
Definition at line 10 of file session.cs.
Member Function Documentation
static void Drive_LFSS.Server_.Session.LoadServerConfig () [static]
Definition at line 28 of file session.cs.
References Drive_LFSS.Server_.Session.serverList.
static void Drive_LFSS.Server_.Session.update (uint diff) [static]
Definition at line 34 of file session.cs.
References Drive_LFSS.Server_.Session.ConnectToServerId(), and Drive_LFSS.Server_.Session.serverList.
static void Drive_LFSS.Server_.Session.ConnectToServerId (ushort serverId) [static]
Definition at line 53 of file session.cs.
References Drive_LFSS.Server_.Session.serverList.
Referenced by Drive_LFSS.Server_.Session.update().
static void Drive_LFSS.Server_.Session.exit () [static]
Definition at line 58 of file session.cs.
References Drive_LFSS.Server_.Session.serverList.
Member Data Documentation
Dictionary<ushort, ServerStruct> Drive_LFSS.Server_.Session.serverList = new Dictionary<ushort, ServerStruct>() [static]
Definition at line 26 of file session.cs.
Referenced by Drive_LFSS.Server_.Session.ConnectToServerId(), Drive_LFSS.Server_.Session.exit(), Drive_LFSS.Server_.Session.LoadServerConfig(), and Drive_LFSS.Server_.Session.update().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/server/session.cs