Drive Live For Speed Server: Drive_LFSS.Program Class Reference
Drive_LFSS.Program Class Reference
Public Member Functions
static bool SetConsoleCtrlHandler (HandlerRoutine Handler, bool AddToReceiveQueud)
delegate bool HandlerRoutine (Ctrl_Types CtrlType)
Static Public Member Functions
static void Main ()
static void Exit ()
Static Public Attributes
static int sleep = 50
static bool MainRun = true
static sLog Log
Static Private Member Functions
static void WriteBanner ()
static void CaptureConsoleCommand ()
static void ConsoleExitTimer ()
static void UnHandleException (object sender, UnhandledExceptionEventArgs args)
static void DisgraceExit (object sender, ConsoleCancelEventArgs args)
static bool DisgraceExit (Ctrl_Types ctrlType)
Static Private Attributes
static Thread ThreadCaptureConsoleCommand = new Thread(new ThreadStart(CaptureConsoleCommand))
static long ticks = DateTime.Now.Ticks
static uint diff = 0
Detailed Description
Definition at line 18 of file drive_lfss.cs.
Member Function Documentation
static bool Drive_LFSS.Program.SetConsoleCtrlHandler (HandlerRoutine Handler, bool AddToReceiveQueud)
Referenced by Drive_LFSS.Program.Main().
delegate bool Drive_LFSS.Program.HandlerRoutine (Ctrl_Types CtrlType)
Referenced by Drive_LFSS.Program.Main().
static void Drive_LFSS.Program.Main () [static]
Definition at line 44 of file drive_lfss.cs.
References Drive_LFSS.Program.diff, Drive_LFSS.Program.DisgraceExit(), Drive_LFSS.Program.HandlerRoutine(), Drive_LFSS.Program.Log, Drive_LFSS.Program.MainRun, Drive_LFSS.Log_.sLog.normal(), Drive_LFSS.Program.SetConsoleCtrlHandler(), Drive_LFSS.Program.sleep, Drive_LFSS.Program.ThreadCaptureConsoleCommand, Drive_LFSS.Program.ticks, Drive_LFSS.Program.UnHandleException(), and Drive_LFSS.Program.WriteBanner().
static void Drive_LFSS.Program.WriteBanner () [static, private]
Definition at line 98 of file drive_lfss.cs.
References Drive_LFSS.Program.Log, and Drive_LFSS.Log_.sLog.normal().
Referenced by Drive_LFSS.Program.Main().
static void Drive_LFSS.Program.CaptureConsoleCommand () [static, private]
Definition at line 117 of file drive_lfss.cs.
References Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Program.Log, Drive_LFSS.Program.MainRun, and Drive_LFSS.Program.sleep.
static void Drive_LFSS.Program.ConsoleExitTimer () [static, private]
Definition at line 132 of file drive_lfss.cs.
References Drive_LFSS.Log_.sLog.error(), and Drive_LFSS.Program.Log.
Referenced by Drive_LFSS.Program.DisgraceExit(), and Drive_LFSS.Program.UnHandleException().
static void Drive_LFSS.Program.UnHandleException (object sender, UnhandledExceptionEventArgs args) [static, private]
Definition at line 145 of file drive_lfss.cs.
References Drive_LFSS.Program.ConsoleExitTimer(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Program.Log, Drive_LFSS.Program.MainRun, and Drive_LFSS.Program.ThreadCaptureConsoleCommand.
Referenced by Drive_LFSS.Program.Main().
static void Drive_LFSS.Program.DisgraceExit (object sender, ConsoleCancelEventArgs args) [static, private]
Definition at line 158 of file drive_lfss.cs.
References Drive_LFSS.Program.ConsoleExitTimer(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Program.Log, Drive_LFSS.Program.MainRun, and Drive_LFSS.Program.ThreadCaptureConsoleCommand.
Referenced by Drive_LFSS.Program.Main().
static bool Drive_LFSS.Program.DisgraceExit (Ctrl_Types ctrlType) [static, private]
Definition at line 170 of file drive_lfss.cs.
References Drive_LFSS.Program.ConsoleExitTimer(), Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Program.Log, Drive_LFSS.Program.MainRun, and Drive_LFSS.Program.ThreadCaptureConsoleCommand.
static void Drive_LFSS.Program.Exit () [static]
Definition at line 182 of file drive_lfss.cs.
References Drive_LFSS.Program.MainRun.
Member Data Documentation
int Drive_LFSS.Program.sleep = 50 [static]
Definition at line 21 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.CaptureConsoleCommand(), and Drive_LFSS.Program.Main().
Thread Drive_LFSS.Program.ThreadCaptureConsoleCommand = new Thread(new ThreadStart(CaptureConsoleCommand)) [static, private]
Definition at line 28 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.DisgraceExit(), Drive_LFSS.Program.Main(), and Drive_LFSS.Program.UnHandleException().
bool Drive_LFSS.Program.MainRun = true [static]
Definition at line 31 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.CaptureConsoleCommand(), Drive_LFSS.Program.DisgraceExit(), Drive_LFSS.Program.Exit(), Drive_LFSS.Program.Main(), and Drive_LFSS.Program.UnHandleException().
long Drive_LFSS.Program.ticks = DateTime.Now.Ticks [static, private]
Definition at line 36 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.Main().
uint Drive_LFSS.Program.diff = 0 [static, private]
Definition at line 37 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.Main().
sLog Drive_LFSS.Program.Log [static]
Definition at line 41 of file drive_lfss.cs.
Referenced by Drive_LFSS.Program.CaptureConsoleCommand(), Drive_LFSS.Program.ConsoleExitTimer(), Drive_LFSS.Program.DisgraceExit(), Drive_LFSS.Program.Main(), Drive_LFSS.Program.UnHandleException(), and Drive_LFSS.Program.WriteBanner().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/drive_lfss/drive_lfss.cs