Drive Live For Speed Server: Drive_LFSS.Server_.Server Class Reference
Drive_LFSS.Server_.Server Class Reference
Public Member Functions
Server (ushort _serverId, InSimSetting _settings)
Server ()
new void update (uint diff)
Public Attributes
bool connectionRequest = true
sLog log
Private Member Functions
void initializeInSimEvents ()
List< byte > GetPlayerListFromLicenceId (byte _licenceId)
byte GetLicenceFromPlayerId (byte _carId)
void SendWelcome (byte uCID)
void MSO_MessageOut (PacketMSO MSO)
void LicenceJoinHost (PacketNCN NCN)
void LicenceLeaveHost (PacketCNL CNL)
void CPR_ClientRenames (PacketCPR CPR)
void TOC_PlayerCarTakeOver (PacketTOC TOC)
void PLL_PlayerLeavesRace (PacketPLL PLL)
void PFL_PlayerFlagsChanged (PacketPFL PFL)
void PLP_PlayerGoesToGarage (PacketPLP PLP)
void NPL_PlayerJoinsRace (PacketNPL NPL)
void LAP_PlayerCompletesLap (PacketLAP LAP)
void FIN_PlayerFinishedRaces (PacketFIN FIN)
void CRS_PlayerResetsCar (PacketCRS CRS)
void PIT_PlayerStopsAtPit (PacketPIT PIT)
void PSF_PitStopFinished (PacketPSF PSF)
void AXO_PlayerHitsAutocrossObject (PacketAXO AXO)
void BFN_PlayerRequestsButtons (PacketBFN BFN)
void BTC_ButtonClicked (PacketBTC BTC)
void BTT_TextBoxOkClicked (PacketBTT BTT)
void PEN_PenaltyChanged (PacketPEN PEN)
void FLG_FlagChanged (PacketFLG FLG)
void PLA_PitLaneChanged (PacketPLA PLA)
void SPX_SplitTime (PacketSPX SPX)
void CCH_CameraChanged (PacketCCH CCH)
void STA_StateChanged (PacketSTA STA)
void ISM_MultiplayerInformation (PacketISM ISM)
void MPE_MultiplayerEnd ()
void CLR_RaceCleared ()
void REO_RaceStartOrder (PacketREO REO)
void RST_RaceStart (PacketRST RST)
void RES_RaceOrQualifyingResult (PacketRES RES)
void REN_RaceEnds ()
void RTP_RaceTime (uint RTP)
void AXC_AutocrossCleared ()
void AXI_AutocrossLayoutInformation (PacketAXI AXI)
void CPP_CameraPosition (PacketCPP CPP)
void VTA_VoteAction (byte VTA)
void VTC_VoteCanceled ()
void VTN_VoteNotify (PacketVTN VTN)
void MCI_CarInformation (PacketMCI MCI)
void NLP_LapNode (PacketNLP NLP)
void III_InSimInfo (PacketIII III)
void VER_InSimVersionInformation (PacketVER VER)
void REPLY_PingReplay ()
Private Attributes
InSimSetting settings
Dictionary< byte, Licence > licenceList = new Dictionary<byte, Licence>()
Dictionary< byte, Car > carList = new Dictionary<byte, Car>()
List< LicenceIdCarIdMap > licenceIdCarIdMap = new List<LicenceIdCarIdMap>()
ushort serverId
long pingTime
CommandServer command
const uint TIMER_PING_PONG = 30000
uint TimerPingPong = 0
Classes
struct LicenceIdCarIdMap
Detailed Description
Definition at line 11 of file server.cs.
Constructor & Destructor Documentation
Drive_LFSS.Server_.Server.Server (ushort _serverId, InSimSetting _settings)
Definition at line 13 of file server.cs.
References Drive_LFSS.Server_.Server.command, Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Server_.Server.initializeInSimEvents(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Server_.Server.serverId, Drive_LFSS.Socket_.InSimSetting.serverIp, and Drive_LFSS.Server_.Server.settings.
Drive_LFSS.Server_.Server.Server ()
Definition at line 31 of file server.cs.
Member Function Documentation
void Drive_LFSS.Server_.Server.initializeInSimEvents () [private]
Definition at line 55 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.Server().
new void Drive_LFSS.Server_.Server.update (uint diff)
Definition at line 64 of file server.cs.
References Drive_LFSS.Socket_.Store.AddToTcpSendingQueud(), Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.InSim.packetStore, Drive_LFSS.Server_.Server.pingTime, Drive_LFSS.Server_.Server.TIMER_PING_PONG, and Drive_LFSS.Server_.Server.TimerPingPong.
List<byte> Drive_LFSS.Server_.Server.GetPlayerListFromLicenceId (byte _licenceId) [private]
Definition at line 85 of file server.cs.
References Drive_LFSS.Server_.Server.licenceIdCarIdMap.
Referenced by Drive_LFSS.Server_.Server.LicenceLeaveHost().
byte Drive_LFSS.Server_.Server.GetLicenceFromPlayerId (byte _carId) [private]
Definition at line 95 of file server.cs.
References Drive_LFSS.Server_.Server.licenceIdCarIdMap.
void Drive_LFSS.Server_.Server.SendWelcome (byte uCID) [private]
Definition at line 104 of file server.cs.
void Drive_LFSS.Server_.Server.MSO_MessageOut (PacketMSO MSO) [private]
Definition at line 114 of file server.cs.
References Drive_LFSS.Log_.sLog.chat(), Drive_LFSS.Server_.Server.command, Drive_LFSS.Socket_.InSimSetting.CommandPrefix, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.CommandServer.Exec(), Drive_LFSS.Server_.Server.licenceList, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketMSO.Msg, Drive_LFSS.Server_.Server.settings, Drive_LFSS.Socket_.PacketMSO.TextStart, and Drive_LFSS.Socket_.PacketMSO.UCID.
void Drive_LFSS.Server_.Server.LicenceJoinHost (PacketNCN NCN) [private]
Definition at line 143 of file server.cs.
References Drive_LFSS.Socket_.PacketNCN.adminStatus, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketNCN.driverName, Drive_LFSS.Socket_.PacketNCN.driverTypeFlag, Drive_LFSS.Log_.sLog.error(), Drive_LFSS.Socket_.PacketNCN.licenceId, Drive_LFSS.Server_.Server.licenceList, Drive_LFSS.Socket_.PacketNCN.licenceName, and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.LicenceLeaveHost (PacketCNL CNL) [private]
Definition at line 155 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.GetPlayerListFromLicenceId(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketCNL.Reason, Drive_LFSS.Socket_.PacketCNL.Total, and Drive_LFSS.Socket_.PacketCNL.UCID.
void Drive_LFSS.Server_.Server.CPR_ClientRenames (PacketCPR CPR) [private]
Definition at line 166 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketCPR.Plate, Drive_LFSS.Socket_.PacketCPR.PName, Drive_LFSS.Socket_.PacketCPR.ReqI, and Drive_LFSS.Socket_.PacketCPR.UCID.
void Drive_LFSS.Server_.Server.TOC_PlayerCarTakeOver (PacketTOC TOC) [private]
Definition at line 170 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketTOC.NewUCID, Drive_LFSS.Socket_.PacketTOC.OldUCID, and Drive_LFSS.Socket_.PacketTOC.PLID.
void Drive_LFSS.Server_.Server.PLL_PlayerLeavesRace (PacketPLL PLL) [private]
Definition at line 174 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketPLL.PLID.
void Drive_LFSS.Server_.Server.PFL_PlayerFlagsChanged (PacketPFL PFL) [private]
Definition at line 181 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketPFL.Flags, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketPFL.PLID, and Drive_LFSS.Socket_.PacketPFL.Spare.
void Drive_LFSS.Server_.Server.PLP_PlayerGoesToGarage (PacketPLP PLP) [private]
Definition at line 186 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketPLP.PLID.
void Drive_LFSS.Server_.Server.NPL_PlayerJoinsRace (PacketNPL NPL) [private]
Definition at line 191 of file server.cs.
References Drive_LFSS.Socket_.PacketNPL.CName, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketNPL.PLID, Drive_LFSS.Socket_.PacketNPL.PName, Drive_LFSS.Socket_.PacketNPL.PType, and Drive_LFSS.Socket_.PacketNPL.UCID.
void Drive_LFSS.Server_.Server.LAP_PlayerCompletesLap (PacketLAP LAP) [private]
Definition at line 196 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketLAP.ETime, Drive_LFSS.Socket_.PacketLAP.Flags, Drive_LFSS.Socket_.PacketLAP.LapsDone, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketLAP.LTime, and Drive_LFSS.Socket_.PacketLAP.PLID.
void Drive_LFSS.Server_.Server.FIN_PlayerFinishedRaces (PacketFIN FIN) [private]
Definition at line 200 of file server.cs.
References Drive_LFSS.Socket_.PacketFIN.BTime, Drive_LFSS.Socket_.PacketFIN.Confirm, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketFIN.Flags, Drive_LFSS.Socket_.PacketFIN.LapsDone, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketFIN.NumStops, Drive_LFSS.Socket_.PacketFIN.PLID, and Drive_LFSS.Socket_.PacketFIN.TTime.
void Drive_LFSS.Server_.Server.CRS_PlayerResetsCar (PacketCRS CRS) [private]
Definition at line 204 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketCRS.PLID.
void Drive_LFSS.Server_.Server.PIT_PlayerStopsAtPit (PacketPIT PIT) [private]
Definition at line 208 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketPIT.FL_Changed, Drive_LFSS.Socket_.PacketPIT.Flags, Drive_LFSS.Socket_.PacketPIT.FR_Changed, Drive_LFSS.Socket_.PacketPIT.LapsDone, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketPIT.NumStops, Drive_LFSS.Socket_.PacketPIT.Penalty, Drive_LFSS.Socket_.PacketPIT.PLID, Drive_LFSS.Socket_.PacketPIT.RL_Changed, Drive_LFSS.Socket_.PacketPIT.RR_Changed, Drive_LFSS.Socket_.PacketPIT.Spare, and Drive_LFSS.Socket_.PacketPIT.Work.
void Drive_LFSS.Server_.Server.PSF_PitStopFinished (PacketPSF PSF) [private]
Definition at line 212 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketPSF.PLID, Drive_LFSS.Socket_.PacketPSF.Spare, and Drive_LFSS.Socket_.PacketPSF.STime.
void Drive_LFSS.Server_.Server.AXO_PlayerHitsAutocrossObject (PacketAXO AXO) [private]
Definition at line 216 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketAXO.PLID.
void Drive_LFSS.Server_.Server.BFN_PlayerRequestsButtons (PacketBFN BFN) [private]
Definition at line 221 of file server.cs.
References Drive_LFSS.Socket_.PacketBFN.ClickID, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketBFN.SubT, and Drive_LFSS.Socket_.PacketBFN.UCID.
void Drive_LFSS.Server_.Server.BTC_ButtonClicked (PacketBTC BTC) [private]
Definition at line 226 of file server.cs.
References Drive_LFSS.Socket_.PacketBTC.CFlags, Drive_LFSS.Socket_.PacketBTC.ClickID, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketBTC.UCID.
void Drive_LFSS.Server_.Server.BTT_TextBoxOkClicked (PacketBTT BTT) [private]
Definition at line 230 of file server.cs.
References Drive_LFSS.Socket_.PacketBTT.ClickID, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketBTT.Text, Drive_LFSS.Socket_.PacketBTT.TypeIn, and Drive_LFSS.Socket_.PacketBTT.UCID.
void Drive_LFSS.Server_.Server.PEN_PenaltyChanged (PacketPEN PEN) [private]
Definition at line 234 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketPEN.NewPen, Drive_LFSS.Socket_.PacketPEN.OldPen, Drive_LFSS.Socket_.PacketPEN.PLID, and Drive_LFSS.Socket_.PacketPEN.Reason.
void Drive_LFSS.Server_.Server.FLG_FlagChanged (PacketFLG FLG) [private]
Definition at line 239 of file server.cs.
References Drive_LFSS.Socket_.PacketFLG.CarBehind, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketFLG.Flag, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketFLG.OffOn, and Drive_LFSS.Socket_.PacketFLG.PLID.
void Drive_LFSS.Server_.Server.PLA_PitLaneChanged (PacketPLA PLA) [private]
Definition at line 244 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketPLA.Fact, Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketPLA.PLID.
void Drive_LFSS.Server_.Server.SPX_SplitTime (PacketSPX SPX) [private]
Definition at line 249 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketSPX.ETime, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketSPX.NumStops, Drive_LFSS.Socket_.PacketSPX.Penalty, Drive_LFSS.Socket_.PacketSPX.PLID, Drive_LFSS.Socket_.PacketSPX.Split, and Drive_LFSS.Socket_.PacketSPX.STime.
void Drive_LFSS.Server_.Server.CCH_CameraChanged (PacketCCH CCH) [private]
Definition at line 254 of file server.cs.
References Drive_LFSS.Socket_.PacketCCH.Camera, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketCCH.PLID.
void Drive_LFSS.Server_.Server.STA_StateChanged (PacketSTA STA) [private]
Definition at line 264 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketSTA.Flags, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketSTA.NumConns, Drive_LFSS.Socket_.PacketSTA.NumP, Drive_LFSS.Socket_.PacketSTA.QualMins, Drive_LFSS.Socket_.PacketSTA.RaceInProg, and Drive_LFSS.Socket_.PacketSTA.ViewPLID.
void Drive_LFSS.Server_.Server.ISM_MultiplayerInformation (PacketISM ISM) [private]
Definition at line 271 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketISM.HName, Drive_LFSS.Socket_.PacketISM.Host, and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.MPE_MultiplayerEnd () [private]
Definition at line 276 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.CLR_RaceCleared () [private]
Definition at line 281 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.REO_RaceStartOrder (PacketREO REO) [private]
Definition at line 286 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketREO.NumP, and Drive_LFSS.Socket_.PacketREO.PLID.
void Drive_LFSS.Server_.Server.RST_RaceStart (PacketRST RST) [private]
Definition at line 291 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketRST.Finish, Drive_LFSS.Socket_.PacketRST.Flags, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketRST.NumNodes, Drive_LFSS.Socket_.PacketRST.NumP, Drive_LFSS.Socket_.PacketRST.QualMins, Drive_LFSS.Socket_.PacketRST.RaceLaps, Drive_LFSS.Socket_.PacketRST.Spare, Drive_LFSS.Socket_.PacketRST.Split1, Drive_LFSS.Socket_.PacketRST.Split2, Drive_LFSS.Socket_.PacketRST.Split3, Drive_LFSS.Socket_.PacketRST.Track, Drive_LFSS.Socket_.PacketRST.Weather, and Drive_LFSS.Socket_.PacketRST.Wind.
void Drive_LFSS.Server_.Server.RES_RaceOrQualifyingResult (PacketRES RES) [private]
Definition at line 298 of file server.cs.
References Drive_LFSS.Socket_.PacketRES.BTime, Drive_LFSS.Socket_.PacketRES.CName, Drive_LFSS.Socket_.PacketRES.Confirm, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketRES.Flags, Drive_LFSS.Socket_.PacketRES.LapsDone, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketRES.NumRes, Drive_LFSS.Socket_.PacketRES.NumStops, Drive_LFSS.Socket_.PacketRES.Plate, Drive_LFSS.Socket_.PacketRES.PLID, Drive_LFSS.Socket_.PacketRES.PName, Drive_LFSS.Socket_.PacketRES.PSeconds, Drive_LFSS.Socket_.PacketRES.ResultNum, Drive_LFSS.Socket_.PacketRES.SpA, Drive_LFSS.Socket_.PacketRES.SpB, Drive_LFSS.Socket_.PacketRES.TTime, and Drive_LFSS.Socket_.PacketRES.UName.
void Drive_LFSS.Server_.Server.REN_RaceEnds () [private]
Definition at line 303 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.RTP_RaceTime (uint RTP) [private]
Definition at line 308 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.AXC_AutocrossCleared () [private]
Definition at line 313 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.AXI_AutocrossLayoutInformation (PacketAXI AXI) [private]
Definition at line 318 of file server.cs.
References Drive_LFSS.Socket_.PacketAXI.AXStart, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketAXI.LName, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketAXI.NumCP, and Drive_LFSS.Socket_.PacketAXI.NumO.
void Drive_LFSS.Server_.Server.CPP_CameraPosition (PacketCPP CPP) [private]
Definition at line 323 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketCPP.Flags, Drive_LFSS.Socket_.PacketCPP.FOV, Drive_LFSS.Socket_.PacketCPP.H, Drive_LFSS.Socket_.PacketCPP.InGameCam, Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketCPP.P, Drive_LFSS.Socket_.PacketCPP.R, Drive_LFSS.Socket_.PacketCPP.Time, Drive_LFSS.Socket_.PacketCPP.ViewPLID, Drive_LFSS.Socket_.PacketCPP.X, Drive_LFSS.Socket_.PacketCPP.Y, and Drive_LFSS.Socket_.PacketCPP.Z.
void Drive_LFSS.Server_.Server.VTA_VoteAction (byte VTA) [private]
Definition at line 328 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.VTC_VoteCanceled () [private]
Definition at line 332 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), and Drive_LFSS.Server_.Server.log.
void Drive_LFSS.Server_.Server.VTN_VoteNotify (PacketVTN VTN) [private]
Definition at line 337 of file server.cs.
References Drive_LFSS.Socket_.PacketVTN.Action, Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketVTN.Spare2, Drive_LFSS.Socket_.PacketVTN.Spare3, and Drive_LFSS.Socket_.PacketVTN.UCID.
void Drive_LFSS.Server_.Server.MCI_CarInformation (PacketMCI MCI) [private]
Definition at line 342 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketMCI.Info, Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketMCI.NumC.
void Drive_LFSS.Server_.Server.NLP_LapNode (PacketNLP NLP) [private]
Definition at line 347 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketNLP.Info, Drive_LFSS.Server_.Server.log, and Drive_LFSS.Socket_.PacketNLP.NumP.
void Drive_LFSS.Server_.Server.III_InSimInfo (PacketIII III) [private]
Definition at line 352 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Server_.Server.log, Drive_LFSS.Socket_.PacketIII.Msg, Drive_LFSS.Socket_.PacketIII.PLID, and Drive_LFSS.Socket_.PacketIII.UCID.
void Drive_LFSS.Server_.Server.VER_InSimVersionInformation (PacketVER VER) [private]
Definition at line 356 of file server.cs.
References Drive_LFSS.Log_.sLog.debug(), Drive_LFSS.Socket_.PacketVER.inSimVersion, Drive_LFSS.Server_.Server.log, Drive_LFSS.Log_.sLog.normal(), Drive_LFSS.Socket_.PacketVER.productVersion, and Drive_LFSS.Socket_.PacketVER.serverVersion.
void Drive_LFSS.Server_.Server.REPLY_PingReplay () [private]
Definition at line 361 of file server.cs.
References Drive_LFSS.Server_.Server.log, Drive_LFSS.Log_.sLog.ping(), and Drive_LFSS.Server_.Server.pingTime.
Member Data Documentation
bool Drive_LFSS.Server_.Server.connectionRequest = true
Definition at line 44 of file server.cs.
InSimSetting Drive_LFSS.Server_.Server.settings [private]
Definition at line 45 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.MSO_MessageOut(), and Drive_LFSS.Server_.Server.Server().
Dictionary<byte, Licence> Drive_LFSS.Server_.Server.licenceList = new Dictionary<byte, Licence>() [private]
Definition at line 47 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.LicenceJoinHost(), and Drive_LFSS.Server_.Server.MSO_MessageOut().
Dictionary<byte, Car> Drive_LFSS.Server_.Server.carList = new Dictionary<byte, Car>() [private]
Definition at line 48 of file server.cs.
List<LicenceIdCarIdMap> Drive_LFSS.Server_.Server.licenceIdCarIdMap = new List<LicenceIdCarIdMap>() [private]
Definition at line 49 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.GetLicenceFromPlayerId(), and Drive_LFSS.Server_.Server.GetPlayerListFromLicenceId().
ushort Drive_LFSS.Server_.Server.serverId [private]
Definition at line 50 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.Server().
long Drive_LFSS.Server_.Server.pingTime [private]
Definition at line 51 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.REPLY_PingReplay(), and Drive_LFSS.Server_.Server.update().
sLog Drive_LFSS.Server_.Server.log
Definition at line 52 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.AXC_AutocrossCleared(), Drive_LFSS.Server_.Server.AXI_AutocrossLayoutInformation(), Drive_LFSS.Server_.Server.AXO_PlayerHitsAutocrossObject(), Drive_LFSS.Server_.Server.BFN_PlayerRequestsButtons(), Drive_LFSS.Server_.Server.BTC_ButtonClicked(), Drive_LFSS.Server_.Server.BTT_TextBoxOkClicked(), Drive_LFSS.Server_.Server.CCH_CameraChanged(), Drive_LFSS.Server_.Server.CLR_RaceCleared(), Drive_LFSS.Server_.Server.CPP_CameraPosition(), Drive_LFSS.Server_.Server.CPR_ClientRenames(), Drive_LFSS.Server_.Server.CRS_PlayerResetsCar(), Drive_LFSS.Server_.Server.FIN_PlayerFinishedRaces(), Drive_LFSS.Server_.Server.FLG_FlagChanged(), Drive_LFSS.Server_.Server.III_InSimInfo(), Drive_LFSS.Server_.Server.ISM_MultiplayerInformation(), Drive_LFSS.Server_.Server.LAP_PlayerCompletesLap(), Drive_LFSS.Server_.Server.LicenceJoinHost(), Drive_LFSS.Server_.Server.LicenceLeaveHost(), Drive_LFSS.Server_.Server.MCI_CarInformation(), Drive_LFSS.Server_.Server.MPE_MultiplayerEnd(), Drive_LFSS.Server_.Server.MSO_MessageOut(), Drive_LFSS.Server_.Server.NLP_LapNode(), Drive_LFSS.Server_.Server.NPL_PlayerJoinsRace(), Drive_LFSS.Server_.Server.PEN_PenaltyChanged(), Drive_LFSS.Server_.Server.PFL_PlayerFlagsChanged(), Drive_LFSS.Server_.Server.PIT_PlayerStopsAtPit(), Drive_LFSS.Server_.Server.PLA_PitLaneChanged(), Drive_LFSS.Server_.Server.PLL_PlayerLeavesRace(), Drive_LFSS.Server_.Server.PLP_PlayerGoesToGarage(), Drive_LFSS.Server_.Server.PSF_PitStopFinished(), Drive_LFSS.Server_.Server.REN_RaceEnds(), Drive_LFSS.Server_.Server.REO_RaceStartOrder(), Drive_LFSS.Server_.Server.REPLY_PingReplay(), Drive_LFSS.Server_.Server.RES_RaceOrQualifyingResult(), Drive_LFSS.Server_.Server.RST_RaceStart(), Drive_LFSS.Server_.Server.RTP_RaceTime(), Drive_LFSS.Server_.Server.Server(), Drive_LFSS.Server_.Server.SPX_SplitTime(), Drive_LFSS.Server_.Server.STA_StateChanged(), Drive_LFSS.Server_.Server.TOC_PlayerCarTakeOver(), Drive_LFSS.Server_.Server.update(), Drive_LFSS.Server_.Server.VER_InSimVersionInformation(), Drive_LFSS.Server_.Server.VTA_VoteAction(), Drive_LFSS.Server_.Server.VTC_VoteCanceled(), and Drive_LFSS.Server_.Server.VTN_VoteNotify().
CommandServer Drive_LFSS.Server_.Server.command [private]
Definition at line 53 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.MSO_MessageOut(), and Drive_LFSS.Server_.Server.Server().
const uint Drive_LFSS.Server_.Server.TIMER_PING_PONG = 30000 [private]
Definition at line 61 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.update().
uint Drive_LFSS.Server_.Server.TimerPingPong = 0 [private]
Definition at line 61 of file server.cs.
Referenced by Drive_LFSS.Server_.Server.update().
The documentation for this class was generated from the following file:
C:/inwork/Drive_LFSS/src/server/server.cs